DROP TABLE IF EXISTS "__PREFIX__crud_logs";
DROP TABLE IF EXISTS "__PREFIX__areas";
DROP TABLE IF EXISTS "__PREFIX__attachments";
DROP TABLE IF EXISTS "__PREFIX__configs";
DROP TABLE IF EXISTS "__PREFIX__captchas";
DROP TABLE IF EXISTS "__PREFIX__tokens";
