import { fieldData } from '@/components/agInput/helper'
import i18n from '@/lang/index'
import { validatorType } from '@/utils/validate'
import { reactive } from 'vue'

export const state: {
    step: 'Start' | 'Design'
    type: string
    table: string
    log: {
        id: number | null
        type: string
    }
} = reactive({
    step: 'Start',
    type: '',
    table: '',
    log: {
        id: null,
        type: '',
    },
})

export const changeStep = (type: string) => {
    state.type = type
    if (type == 'start') {
        state.step = 'Start'
        state.table = ''
        state.log.id = null
        state.log.type = ''
    } else {
        // 打开设计器
        state.step = 'Design'
    }
}

/**
 * 字段修改类型标识
 * 其中的改排序需要在表结构变更完成之后再单独处理所以也有独立标识
 */
export type TableDesignChangeType = 'change-field-name' | 'del-field' | 'add-field' | 'change-field-attr'

export interface TableDesignChange {
    type: TableDesignChangeType
    // 字段在设计器中的数组 index
    index?: number
    // 字段名称（重命名、修改属性、删除、添加）
    name: string
    // 字段新名称（重命名）
    newName: string
    // 是否同步到数据表
    sync?: boolean
}

export interface FieldItem {
    index?: number
    title: string
    name: string
    // 字段类型:varchar、numeric 这种预设模式，通过 length 设置长度
    type: string
    // 自定义字段类型:varchar(128) 这种自定义的模式，直接填写字段类型完整定义
    dataType?: string
    length: number
    precision: number
    default?: string
    defaultType: 'INPUT' | 'EMPTY STRING' | 'NULL' | 'NONE'
    null: boolean
    primaryKey: boolean
    unique: boolean
    generated?: 'GENERATED ALWAYS' | 'GENERATED BY DEFAULT'
    comment: string
    // 字段设计类型，如:pk,weigh 这种预设了设计器属性的字段类型
    designType: string
    formBuildExclude?: boolean
    tableBuildExclude?: boolean
    table: AnyObj
    form: AnyObj
    uuid?: string
}

export const fieldItem: {
    common: FieldItem[]
    base: FieldItem[]
    senior: FieldItem[]
} = {
    common: [
        {
            title: i18n.global.t('crud.index.primaryKey'),
            name: 'id',
            comment: 'ID',
            designType: 'pk',
            formBuildExclude: true,
            table: {},
            form: {},
            ...fieldData.int,
            defaultType: 'NONE',
            null: false,
            primaryKey: true,
            generated: 'GENERATED ALWAYS',
        },
        {
            title: i18n.global.t('common.status'),
            name: 'status',
            comment: i18n.global.t('common.status'),
            designType: 'switch',
            table: {},
            form: {},
            ...fieldData.switch,
            default: 'true',
        },
        {
            title: i18n.global.t('crud.index.remark'),
            name: 'remark',
            comment: i18n.global.t('crud.index.remark'),
            designType: 'textarea',
            tableBuildExclude: true,
            table: {},
            form: {},
            ...fieldData.textarea,
        },
        {
            title: i18n.global.t('crud.index.weigh'),
            name: 'weigh',
            comment: i18n.global.t('common.weigh'),
            designType: 'weigh',
            table: {},
            form: {},
            ...fieldData.int,
            null: true,
            defaultType: 'NULL',
        },
        {
            title: i18n.global.t('common.updatedAt'),
            name: 'updated_at',
            comment: i18n.global.t('common.updatedAt'),
            designType: 'datetime',
            formBuildExclude: true,
            table: {},
            form: {},
            ...fieldData.datetime,
        },
        {
            title: i18n.global.t('common.createdAt'),
            name: 'created_at',
            comment: i18n.global.t('common.createdAt'),
            designType: 'datetime',
            formBuildExclude: true,
            table: {},
            form: {},
            ...fieldData.datetime,
        },
        {
            title: i18n.global.t('crud.index.remoteSelect'),
            name: 'remote_select',
            comment: i18n.global.t('common.remoteSelect'),
            designType: 'remoteSelect',
            tableBuildExclude: true,
            table: {},
            form: {},
            ...fieldData.remoteSelect,
        },
    ],
    base: [
        {
            title: i18n.global.t('common.string'),
            name: 'string',
            comment: i18n.global.t('common.string'),
            designType: 'string',
            table: {},
            form: {},
            ...fieldData.string,
        },
        {
            title: i18n.global.t('common.image'),
            name: 'image',
            comment: i18n.global.t('common.image'),
            designType: 'image',
            table: {},
            form: {},
            ...fieldData.image,
        },
        {
            title: i18n.global.t('common.file'),
            name: 'file',
            comment: i18n.global.t('common.file'),
            designType: 'file',
            tableBuildExclude: true,
            table: {},
            form: {},
            ...fieldData.file,
        },
        {
            title: i18n.global.t('common.radio'),
            name: 'radio',
            comment: i18n.global.t('crud.index.radio'),
            designType: 'radio',
            table: {},
            form: {},
            ...fieldData.radio,
            null: false,
            default: 'opt0',
            defaultType: 'INPUT',
        },
        {
            title: i18n.global.t('common.checkbox'),
            name: 'checkbox',
            comment: i18n.global.t('crud.index.checkbox'),
            designType: 'checkbox',
            table: {},
            form: {},
            ...fieldData.checkbox,
            default: 'opt0,opt1',
            defaultType: 'INPUT',
        },
        {
            title: i18n.global.t('common.select'),
            name: 'select',
            comment: i18n.global.t('crud.index.select'),
            designType: 'select',
            table: {},
            form: {},
            ...fieldData.select,
            null: false,
            default: 'opt0',
            defaultType: 'INPUT',
        },
        {
            title: i18n.global.t('common.switch'),
            name: 'switch',
            comment: i18n.global.t('common.switch'),
            designType: 'switch',
            table: {},
            form: {},
            ...fieldData.switch,
        },
        {
            title: i18n.global.t('common.richText'),
            name: 'editor',
            comment: i18n.global.t('common.richText'),
            designType: 'editor',
            tableBuildExclude: true,
            table: {},
            form: {},
            ...fieldData.editor,
        },
        {
            title: i18n.global.t('common.textarea'),
            name: 'textarea',
            comment: i18n.global.t('common.textarea'),
            designType: 'textarea',
            tableBuildExclude: true,
            table: {},
            form: {},
            ...fieldData.textarea,
        },
        {
            title: i18n.global.t('common.integer'),
            name: 'int',
            comment: i18n.global.t('common.integer'),
            designType: 'int',
            table: {},
            form: {},
            ...fieldData.int,
        },
        {
            title: i18n.global.t('common.float'),
            name: 'float',
            comment: i18n.global.t('common.float'),
            designType: 'float',
            table: {},
            form: {},
            ...fieldData.number,
        },
        {
            title: i18n.global.t('common.password'),
            name: 'password',
            comment: i18n.global.t('common.password'),
            designType: 'password',
            tableBuildExclude: true,
            table: {},
            form: {},
            ...fieldData.password,
        },
        {
            title: i18n.global.t('common.year'),
            name: 'year',
            comment: i18n.global.t('common.year'),
            designType: 'year',
            table: {},
            form: {},
            ...fieldData.year,
        },
        {
            title: i18n.global.t('common.date'),
            name: 'date',
            comment: i18n.global.t('common.date'),
            designType: 'date',
            table: {},
            form: {},
            ...fieldData.date,
        },
        {
            title: i18n.global.t('common.time'),
            name: 'time',
            comment: i18n.global.t('common.time'),
            designType: 'time',
            table: {},
            form: {},
            ...fieldData.time,
        },
        {
            title: i18n.global.t('common.datetime'),
            name: 'datetime',
            designType: 'datetime',
            comment: i18n.global.t('common.datetime'),
            table: {},
            form: {},
            ...fieldData.datetime,
        },
    ],
    senior: [
        {
            title: i18n.global.t('common.array'),
            name: 'array',
            comment: i18n.global.t('common.array'),
            designType: 'array',
            tableBuildExclude: true,
            table: {},
            form: {},
            ...fieldData.array,
        },
        {
            title: i18n.global.t('common.areaSelect'),
            name: 'area',
            comment: i18n.global.t('common.areaSelect'),
            designType: 'areaSelect',
            table: {},
            form: {},
            ...fieldData.areaSelect,
        },
        {
            title: i18n.global.t('common.iconSelect'),
            name: 'icon',
            comment: i18n.global.t('common.iconSelect'),
            designType: 'iconSelect',
            table: {},
            form: {},
            ...fieldData.iconSelect,
        },
        {
            title: i18n.global.t('common.color') + i18n.global.t('common.choice'),
            name: 'color',
            comment: i18n.global.t('common.color') + i18n.global.t('common.choice'),
            designType: 'color',
            table: {},
            form: {},
            ...fieldData.color,
        },
        {
            title: i18n.global.t('common.image') + i18n.global.t('common.multiple'),
            name: 'images',
            comment: i18n.global.t('common.image'),
            designType: 'images',
            table: {},
            form: {},
            ...fieldData.images,
        },
        {
            title: i18n.global.t('common.file') + i18n.global.t('common.multiple'),
            name: 'files',
            comment: i18n.global.t('common.file'),
            designType: 'files',
            tableBuildExclude: true,
            table: {},
            form: {},
            ...fieldData.files,
        },
        {
            title: i18n.global.t('common.select') + i18n.global.t('common.multiple'),
            name: 'selects',
            comment: i18n.global.t('crud.index.select'),
            designType: 'selects',
            table: {},
            form: {},
            ...fieldData.selects,
        },
        {
            title: i18n.global.t('crud.index.remoteSelects'),
            name: 'remote_select',
            comment: i18n.global.t('common.remoteSelect') + i18n.global.t('common.multiple'),
            designType: 'remoteSelects',
            tableBuildExclude: true,
            table: {},
            form: {},
            ...fieldData.remoteSelects,
        },
    ],
}

const tableBaseAttr = {
    // 渲染方式
    render: {
        type: 'select',
        value: 'none',
        options: {
            none: i18n.global.t('common.none'),
            icon: 'Icon',
            switch: i18n.global.t('common.switch'),
            image: i18n.global.t('common.image'),
            images: i18n.global.t('common.images'),
            tag: 'Tag',
            tags: 'Tags',
            url: 'URL',
            datetime: i18n.global.t('common.datetime'),
            color: i18n.global.t('common.color'),
        },
    },
    // 公共搜索比较符号
    operator: {
        type: 'select',
        value: 'eq',
        options: {
            false: i18n.global.t('crud.index.disableSearch'),
            eq: 'eq =',
            ne: 'ne !=',
            gt: 'gt >',
            egt: 'egt >=',
            lt: 'lt <',
            elt: 'elt <=',
            LIKE: 'LIKE',
            'NOT LIKE': 'NOT LIKE',
            ILIKE: 'ILIKE',
            'NOT ILIKE': 'NOT ILIKE',
            IN: 'IN',
            'NOT IN': 'NOT IN',
            BETWEEN: 'BETWEEN',
            'NOT BETWEEN': 'NOT BETWEEN',
            NULL: 'NULL',
            'NOT NULL': 'NOT NULL',
        },
    },
    // 公共搜索输入框渲染方式
    comSearchRender: {
        type: 'select',
        value: 'string',
        options: {
            string: i18n.global.t('common.string'),
            select: i18n.global.t('common.select'),
            remoteSelect: i18n.global.t('common.remoteSelect'),
            time: i18n.global.t('common.time') + i18n.global.t('common.choice'),
            date: i18n.global.t('common.date') + i18n.global.t('common.choice'),
            datetime: i18n.global.t('common.datetime') + i18n.global.t('common.choice'),
        },
    },
    // 公共搜索输入框自定义属性
    comSearchInputAttr: {
        type: 'textarea',
        value: '',
        placeholder: i18n.global.t('common.strAttrTip'),
        attr: {
            rows: 3,
        },
    },
    // 排序
    sortable: {
        type: 'select',
        value: 'false',
        options: {
            false: i18n.global.t('common.disable'),
            custom: i18n.global.t('common.enable'),
        },
    },
}

const formBaseAttr = {
    // 验证规则
    validator: {
        type: 'selects',
        value: [],
        options: validatorType,
    },
    // 验证规则错误消息
    validatorMsg: {
        type: 'textarea',
        value: '',
        placeholder: i18n.global.t('crud.index.validateMessage'),
        attr: {
            rows: 3,
        },
    },
}

export const getTableAttr = (type: keyof typeof tableBaseAttr, val: string) => {
    return {
        ...tableBaseAttr[type],
        value: val,
    }
}

const getFormAttr = (type: keyof typeof formBaseAttr, val: string[]) => {
    return {
        ...formBaseAttr[type],
        value: val,
    }
}

export const designTypes: AnyObj = {
    pk: {
        name: i18n.global.t('crud.index.primaryKey'),
        table: {
            width: {
                type: 'number',
                value: 70,
            },
            operator: getTableAttr('operator', 'BETWEEN'),
            sortable: getTableAttr('sortable', 'custom'),
        },
        form: {},
    },
    weigh: {
        name: i18n.global.t('crud.index.weigh'),
        table: {
            operator: getTableAttr('operator', 'BETWEEN'),
            sortable: getTableAttr('sortable', 'custom'),
        },
        form: formBaseAttr,
    },
    datetime: {
        name: i18n.global.t('common.datetime'),
        table: {
            render: getTableAttr('render', 'datetime'),
            operator: getTableAttr('operator', 'BETWEEN'),
            comSearchRender: getTableAttr('comSearchRender', 'datetime'),
            comSearchInputAttr: getTableAttr('comSearchInputAttr', ''),
            sortable: getTableAttr('sortable', 'custom'),
            width: {
                type: 'number',
                value: 160,
            },
        },
        form: formBaseAttr,
    },
    string: {
        name: i18n.global.t('common.string'),
        table: {
            render: getTableAttr('render', 'none'),
            sortable: getTableAttr('sortable', 'false'),
            operator: getTableAttr('operator', 'ILIKE'),
        },
        form: formBaseAttr,
    },
    password: {
        name: i18n.global.t('common.password'),
        table: {
            operator: getTableAttr('operator', 'false'),
        },
        form: {
            ...formBaseAttr,
            validator: getFormAttr('validator', ['password']),
        },
    },
    int: {
        name: i18n.global.t('common.integer'),
        table: {
            render: getTableAttr('render', 'none'),
            sortable: getTableAttr('sortable', 'custom'),
            operator: getTableAttr('operator', 'BETWEEN'),
        },
        form: {
            ...formBaseAttr,
            validator: getFormAttr('validator', ['number']),
            step: {
                type: 'number',
                value: 1,
            },
        },
    },
    float: {
        name: i18n.global.t('common.float'),
        table: {
            render: getTableAttr('render', 'none'),
            sortable: getTableAttr('sortable', 'custom'),
            operator: getTableAttr('operator', 'BETWEEN'),
        },
        form: {
            ...formBaseAttr,
            validator: getFormAttr('validator', ['number']),
            step: {
                type: 'number',
                value: 1,
            },
        },
    },
    radio: {
        name: i18n.global.t('common.radio'),
        table: {
            operator: getTableAttr('operator', 'eq'),
            sortable: getTableAttr('sortable', 'false'),
            render: getTableAttr('render', 'tag'),
        },
        form: formBaseAttr,
    },
    checkbox: {
        name: i18n.global.t('common.checkbox'),
        table: {
            sortable: getTableAttr('sortable', 'false'),
            render: getTableAttr('render', 'tags'),
            operator: getTableAttr('operator', 'ILIKE'),
        },
        form: formBaseAttr,
    },
    switch: {
        name: i18n.global.t('common.switch'),
        table: {
            operator: getTableAttr('operator', 'eq'),
            sortable: getTableAttr('sortable', 'custom'),
            render: getTableAttr('render', 'switch'),
        },
        form: formBaseAttr,
    },
    textarea: {
        name: i18n.global.t('common.textarea'),
        table: {
            operator: getTableAttr('operator', 'false'),
        },
        form: {
            ...formBaseAttr,
            rows: {
                type: 'number',
                value: 3,
            },
        },
    },
    array: {
        name: i18n.global.t('common.array'),
        table: {
            operator: getTableAttr('operator', 'false'),
        },
        form: formBaseAttr,
    },
    year: {
        name: i18n.global.t('common.year') + i18n.global.t('common.choice'),
        table: {
            operator: getTableAttr('operator', 'BETWEEN'),
            sortable: getTableAttr('sortable', 'custom'),
        },
        form: formBaseAttr,
    },
    date: {
        name: i18n.global.t('common.date') + i18n.global.t('common.choice'),
        table: {
            operator: getTableAttr('operator', 'BETWEEN'),
            comSearchRender: getTableAttr('comSearchRender', 'date'),
            comSearchInputAttr: getTableAttr('comSearchInputAttr', ''),
            sortable: getTableAttr('sortable', 'custom'),
        },
        form: {
            ...formBaseAttr,
            validator: getFormAttr('validator', ['date']),
        },
    },
    time: {
        name: i18n.global.t('common.time') + i18n.global.t('common.choice'),
        table: {
            operator: getTableAttr('operator', 'BETWEEN'),
            comSearchRender: getTableAttr('comSearchRender', 'time'),
            comSearchInputAttr: getTableAttr('comSearchInputAttr', ''),
            sortable: getTableAttr('sortable', 'false'),
        },
        form: formBaseAttr,
    },
    select: {
        name: i18n.global.t('common.select'),
        table: {
            operator: getTableAttr('operator', 'eq'),
            sortable: getTableAttr('sortable', 'false'),
            render: getTableAttr('render', 'tag'),
        },
        form: {
            ...formBaseAttr,
            selectMultiple: {
                type: 'switch',
                value: false,
            },
        },
    },
    selects: {
        name: i18n.global.t('common.select') + i18n.global.t('common.multiple'),
        table: {
            sortable: getTableAttr('sortable', 'false'),
            render: getTableAttr('render', 'tags'),
            operator: getTableAttr('operator', 'ILIKE'),
        },
        form: {
            ...formBaseAttr,
            selectMultiple: {
                type: 'switch',
                value: true,
            },
        },
    },
    remoteSelect: {
        name: i18n.global.t('common.remoteSelect') + i18n.global.t('common.choice'),
        table: {
            render: getTableAttr('render', 'tags'),
            operator: getTableAttr('operator', 'ILIKE'),
            comSearchRender: getTableAttr('comSearchRender', 'string'),
            comSearchInputAttr: getTableAttr('comSearchInputAttr', ''),
        },
        form: {
            ...formBaseAttr,
            selectMultiple: {
                type: 'switch',
                value: false,
            },
            remotePk: {
                type: 'string',
                value: 'id',
            },
            remoteField: {
                type: 'string',
                value: 'name',
            },
            remoteTable: {
                type: 'string',
                value: '',
            },
            remoteModelFile: {
                type: 'string',
                value: '',
            },
            remoteModelName: {
                type: 'string',
                value: '',
            },
            remoteModelPackage: {
                type: 'string',
                value: '',
            },
            remoteCrudLog: {
                type: 'hidden',
                value: 0,
            },
            relationFields: {
                type: 'string',
                value: '',
            },
            remoteUrl: {
                type: 'string',
                value: '',
                placeholder: i18n.global.t('crud.index.remoteSelectRequestTip'),
            },
            remoteSourceConfigType: {
                type: 'hidden',
                value: '',
            },
        },
    },
    remoteSelects: {
        name: i18n.global.t('common.remoteSelect') + i18n.global.t('common.choice') + i18n.global.t('common.multiple'),
        table: {
            render: getTableAttr('render', 'tags'),
            operator: getTableAttr('operator', 'ILIKE'),
            comSearchRender: getTableAttr('comSearchRender', 'remoteSelect'),
            comSearchInputAttr: getTableAttr('comSearchInputAttr', ''),
        },
        form: {
            ...formBaseAttr,
            selectMultiple: {
                type: 'switch',
                value: true,
            },
            remotePk: {
                type: 'string',
                value: 'id',
            },
            remoteField: {
                type: 'string',
                value: 'name',
            },
            remoteTable: {
                type: 'string',
                value: '',
            },
            remoteModelFile: {
                type: 'string',
                value: '',
            },
            remoteModelName: {
                type: 'string',
                value: '',
            },
            remoteModelPackage: {
                type: 'string',
                value: '',
            },
            remoteCrudLog: {
                type: 'hidden',
                value: 0,
            },
            relationFields: {
                type: 'string',
                value: '',
            },
            remoteUrl: {
                type: 'string',
                value: '',
                placeholder: i18n.global.t('crud.index.remoteSelectRequestTip'),
            },
            remoteSourceConfigType: {
                type: 'hidden',
                value: '',
            },
        },
    },
    editor: {
        name: i18n.global.t('common.richText'),
        table: {
            operator: getTableAttr('operator', 'false'),
        },
        form: {
            ...formBaseAttr,
            validator: getFormAttr('validator', ['richTextRequired']),
        },
    },
    areaSelect: {
        name: i18n.global.t('common.areaSelect'),
        table: {
            operator: getTableAttr('operator', 'false'),
        },
        form: formBaseAttr,
    },
    image: {
        name: i18n.global.t('common.image') + i18n.global.t('common.upload'),
        table: {
            render: getTableAttr('render', 'image'),
            operator: getTableAttr('operator', 'false'),
        },
        form: {
            ...formBaseAttr,
            imageMultiple: {
                type: 'switch',
                value: false,
            },
        },
    },
    images: {
        name: i18n.global.t('common.image') + i18n.global.t('common.upload') + i18n.global.t('common.multiple'),
        table: {
            render: getTableAttr('render', 'images'),
            operator: getTableAttr('operator', 'false'),
        },
        form: {
            ...formBaseAttr,
            imageMultiple: {
                type: 'switch',
                value: true,
            },
        },
    },
    file: {
        name: i18n.global.t('common.file') + i18n.global.t('common.upload'),
        table: {
            render: getTableAttr('render', 'none'),
            operator: getTableAttr('operator', 'false'),
        },
        form: {
            ...formBaseAttr,
            fileMultiple: {
                type: 'switch',
                value: false,
            },
        },
    },
    files: {
        name: i18n.global.t('common.file') + i18n.global.t('common.upload') + i18n.global.t('common.multiple'),
        table: {
            render: getTableAttr('render', 'none'),
            operator: getTableAttr('operator', 'false'),
        },
        form: {
            ...formBaseAttr,
            fileMultiple: {
                type: 'switch',
                value: true,
            },
        },
    },
    iconSelect: {
        name: i18n.global.t('common.iconSelect'),
        table: {
            render: getTableAttr('render', 'icon'),
            operator: getTableAttr('operator', 'false'),
        },
        form: formBaseAttr,
    },
    color: {
        name: i18n.global.t('common.color') + i18n.global.t('common.choice'),
        table: {
            render: getTableAttr('render', 'color'),
            operator: getTableAttr('operator', 'false'),
        },
        form: formBaseAttr,
    },
}

export const tableFieldsKey = ['quickSearchField', 'formFields', 'columnFields']
