package table

import (
	"context"
	"strings"

	"github.com/ai-go-hub/ai-go-admin/internal/infra/database"
	"github.com/ai-go-hub/ai-go-admin/pkg/util"
)

// FieldItem 解析出的数据表字段数据
type FieldItem struct {
	Title       string  `json:"title"`
	Name        string  `json:"name"`
	Type        string  `json:"type"`
	DataType    string  `json:"dataType,omitempty"`
	Length      int     `json:"length"`
	Precision   int     `json:"precision"`
	Default     *string `json:"default,omitempty"`
	DefaultType string  `json:"defaultType"`
	Null        bool    `json:"null"`
	PrimaryKey  bool    `json:"primaryKey"`
	Unique      bool    `json:"unique"`
	Generated   string  `json:"generated,omitempty"`
	Comment     string  `json:"comment"`
	DesignType  string  `json:"designType"`
}

// RawColumn 数据表字段原始元数据
type RawColumn struct {
	Name               string
	DataType           string
	Length             *int
	NumericPrecision   *int
	NumericScale       *int
	IsNullable         string
	ColumnDefault      *string
	IsIdentity         string
	IdentityGeneration string
	Comment            string
	IsPK               bool
	IsUnique           bool
}

// columnsSQL 查询数据表字段元数据
const columnsSQL = `
SELECT
    c.column_name AS "name",
    c.data_type AS "data_type",
    c.character_maximum_length AS "length",
    c.numeric_precision AS "numeric_precision",
    c.numeric_scale AS "numeric_scale",
    c.is_nullable AS "is_nullable",
    c.column_default AS "column_default",
    c.is_identity AS "is_identity",
    c.identity_generation AS "identity_generation",
    COALESCE(pg_catalog.col_description(t.oid, c.ordinal_position), '') AS "comment",
    EXISTS (
        SELECT 1 FROM pg_catalog.pg_index i
        WHERE i.indrelid = t.oid
            AND i.indisprimary
            AND c.ordinal_position = ANY(i.indkey)
    ) AS "is_pk",
    EXISTS (
        SELECT 1 FROM pg_catalog.pg_index i
        WHERE i.indrelid = t.oid
            AND i.indisunique
            AND NOT i.indisprimary
            AND array_length(i.indkey, 1) = 1
            AND c.ordinal_position = ANY(i.indkey)
    ) AS "is_unique"
FROM information_schema.columns c
JOIN pg_catalog.pg_class t ON t.relname = c.table_name
JOIN pg_catalog.pg_namespace n ON n.oid = t.relnamespace AND n.nspname = c.table_schema
WHERE c.table_schema = current_schema()
    AND c.table_name = ?
ORDER BY c.ordinal_position
`

// ParseFieldData 解析指定数据表的字段数据
func ParseFieldData(ctx context.Context, table string) ([]FieldItem, error) {
	db := database.DB().WithContext(ctx)

	var cols []RawColumn
	if err := db.Raw(columnsSQL, table).Scan(&cols).Error; err != nil {
		return nil, err
	}

	fields := make([]FieldItem, 0, len(cols))
	for _, col := range cols {
		fields = append(fields, buildFieldItem(col))
	}

	return fields, nil
}

// buildFieldItem 构建字段数据
func buildFieldItem(col RawColumn) FieldItem {
	typ := normalizeType(col.DataType)
	length, precision := resolveLengthPrecision(col, typ)

	title := col.Comment
	if title == "" {
		title = col.Name
	}

	generated := ""
	if col.IsIdentity == "YES" {
		switch col.IdentityGeneration {
		case "ALWAYS":
			generated = "GENERATED ALWAYS"
		case "BY DEFAULT":
			generated = "GENERATED BY DEFAULT"
		}
	}

	defaultType, defaultValue := resolveDefault(col)

	return FieldItem{
		Title:       title,
		Name:        col.Name,
		Type:        typ,
		Length:      length,
		Precision:   precision,
		Default:     defaultValue,
		DefaultType: defaultType,
		Null:        col.IsNullable == "YES",
		PrimaryKey:  col.IsPK,
		Unique:      col.IsUnique,
		Generated:   generated,
		Comment:     col.Comment,
		DesignType:  resolveDesignType(col.Name, typ, col.IsPK),
	}
}

// resolveDefault 解析字段默认值与默认值类型
func resolveDefault(col RawColumn) (string, *string) {
	if col.ColumnDefault != nil {
		d := strings.TrimSpace(*col.ColumnDefault)
		if strings.EqualFold(d, "NULL") {
			return "NULL", nil
		}
		if strings.HasPrefix(d, "nextval(") {
			return "NONE", nil
		}
		v := cleanDefault(d)
		if v == "" {
			return "EMPTY STRING", nil
		}
		return "INPUT", &v
	}
	if col.IsNullable == "YES" {
		return "NULL", nil
	}
	return "NONE", nil
}

// cleanDefault 清洗默认值，去掉 ::类型 后缀与引号
func cleanDefault(def string) string {
	if i := strings.Index(def, "::"); i >= 0 {
		def = def[:i]
	}
	def = strings.TrimSpace(def)
	if len(def) >= 2 && def[0] == '\'' && def[len(def)-1] == '\'' {
		def = def[1 : len(def)-1]
	}
	return def
}

// normalizeType 归一化数据库字段类型为前端预设类型
func normalizeType(dataType string) string {
	switch dataType {
	case "character varying":
		return "varchar"
	case "character":
		return "char"
	case "timestamp with time zone":
		return "timestamptz"
	case "timestamp without time zone":
		return "timestamp"
	case "time with time zone":
		return "timetz"
	case "time without time zone":
		return "time"
	case "double precision":
		return "double precision"
	case "json", "jsonb":
		return "jsonb"
	case "ARRAY":
		return "array"
	default:
		return dataType
	}
}

// resolveLengthPrecision 根据字段类型解析长度与精度
func resolveLengthPrecision(col RawColumn, typ string) (int, int) {
	switch typ {
	case "varchar", "char":
		return util.FromPtr(col.Length), 0
	case "numeric":
		return util.FromPtr(col.NumericPrecision), util.FromPtr(col.NumericScale)
	case "bigint", "integer", "smallint", "timestamp", "timestamptz", "time", "timetz":
		return util.FromPtr(col.NumericPrecision), 0
	default:
		return 0, 0
	}
}

// fieldDataMap 字段类型映射（仅含无歧义的），其余由字段名推断或按类型兜底
var fieldDataMap = map[string]string{
	"text":        "textarea",
	"timestamptz": "datetime",
}

// designTypeNames 前端 designTypes 的键，用于按字段名包含推断（长优先）
var designTypeNames = []string{
	"datetime", "checkbox", "textarea", "password",
	"selects",
	"string", "switch", "editor", "images", "select",
	"weigh", "float", "radio", "array", "image", "files", "color",
	"year", "date", "time", "file",
	"int",
}

// designTypeNameMap 按字段名精确匹配推断 designType
var designTypeNameMap = map[string]string{
	"status": "radio",
	"avatar": "image",
	"icon":   "iconSelect",
	"area":   "areaSelect",
}

// resolveDesignType 解析字段的 designType
func resolveDesignType(name, typ string, isPK bool) string {
	if isPK {
		return "pk"
	}
	// 字段类型在 fieldDataMap 中无歧义对应时直接确定 designType
	if dt := fieldDataMap[typ]; dt != "" {
		return dt
	}
	if dt := inferByName(name); dt != "" {
		return dt
	}
	return defaultByType(typ)
}

// inferByName 按字段名称推断 designType
func inferByName(name string) string {
	if strings.HasSuffix(name, "_ids") {
		return "remoteSelects"
	}
	if strings.HasSuffix(name, "_id") {
		return "remoteSelect"
	}
	// 精确匹配先行
	if dt, ok := designTypeNameMap[name]; ok {
		return dt
	}
	for _, dt := range designTypeNames {
		if strings.Contains(name, dt) {
			return dt
		}
	}
	return ""
}

// defaultByType 按字段类型兜底默认 designType
func defaultByType(typ string) string {
	switch typ {
	case "varchar", "char", "uuid":
		return "string"
	case "bigint", "integer", "smallint":
		return "int"
	case "numeric", "real", "double precision":
		return "float"
	case "boolean":
		return "switch"
	case "jsonb", "json":
		return "array"
	case "text":
		return "textarea"
	case "date":
		return "date"
	case "timestamp", "timestamptz":
		return "datetime"
	case "time", "timetz":
		return "time"
	default:
		return "string"
	}
}
